remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Michael's Portfolio
description: Portfolio to showcase projects

show_downloads: "false"
